---
title: "get-power"
author: "Dominick Lemas"
date: "7/12/2019"
output: html_document
---

Document run at: `r Sys.time()`.
Description: Emoncms API system for emoncms project

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(keyringr)
library(httr)
library(dplyr)
library(lubridate)
library(jsonlite)
library(tidyverse)
library(scales)
source("~/GitHub/emoncms/config/utils.R")
options(scipen = 999)

# output diectory
data.dir=paste0(Sys.getenv("USERPROFILE"),"\\Dropbox (UFL)\\02_Projects\\EMONCMS\\data\\")
```


```{r}
# # Intall Run to get data

api_key=get_API_token("emoncms_api")
power=getKWData(api_key, "2019-07-01", 40)
saveRDS(power, file=paste0(data.dir,"power.rds"))
```

# Data Description

Data stored: 
`r data.dir`

Start date:
`r first(power$date_hms)`

End date:
`r last(power$date_hms)`

# Explore the Data

```{r}
power_1=power %>%
  mutate(month=month(date_hms),
         day=day(date_hms),
         hour=hour(date_hms))

ggplot(data = power_1, aes(x=date_hms, y=kwh))+
  geom_line(color = "#00AFBB")

```


