
# site overview
overview=siteoverview(api_key)
   

# timeframe
#----------

 full.url="https://monitoringapi.solaredge.com/site/1219503/timeFrameEnergy?startDate=2019-10-15&endDate=2020-06-08&api_key="

   # pull data
  timeframe <- fromJSON(full.url);timeframe



# start & end dates
# URL: /site/{siteId}/dataPeriod

full.url="https://monitoringapi.solaredge.com/site/1219503/dataPeriod?api_key=" 


   # pull data
  data_range <- fromJSON(full.url);data_range



# Environmental Benefit
#----------------------

https://monitoringapi.solaredge.com/site/2/envBenefits?systemUnits=Imperial&api_key= 


  # url
    url="https://monitoringapi.solaredge.com/site/";url
  
  # API parameters
    site_ID="1219503/"
    param1="envBenefits?"
    param2="systemUnits=Imperial&"
    
  
  
  full.url=paste0(url,site_ID,param1,param2,api_key);full.url # min
  
   # pull data
  power_new <- fromJSON(full.url);power_new

    

# Inventory SolarEdge Equipment
#------------------------------

https://monitoringapi.solaredge.com/site/2/inventory?api_key= 

  # url
    url="https://monitoringapi.solaredge.com/site/";url
  
  # API parameters
    site_ID="1219503/"
    param1="inventory?"
  
  
  full.url=paste0(url,site_ID,param1,api_key);full.url # min
  
   # pull data
  power_new <- fromJSON(full.url)



#' Update Home Solar Power Data
#' Queries the SolarEdge API to UPDATE home solar power (wats)
#' every 60 seconds from start time to present
#' https://emoncms.org/site/api#feed
#' @return data.frame containing: unix-time, wat, date-time
solarKWData <- function(api_key, power){
  
  # start date/time
  start.time=last(power$date_hms)+30
  start.unix=as.numeric(start.time)*1000 
  
  # end date/time
  stop.time=Sys.time()
  end.unix=as.numeric(stop.time)*1000 
  
  # url
  url="https://monitoringapi.solaredge.com/site/";url
  
  # API parameters
  site_ID=1219503
  
  
  full.url=paste0(url,api_key);full.url # min
  
  # pull data
  power_new <- fromJSON(full.url) %>%
  as.data.frame() %>%
  mutate(date_hms=as.POSIXct(V1/1000, origin="1970-01-01")) %>%
  rename(kwh=V2, time_unix=V1) 

# combine with old data
power_update <-rbind(power,power_new)

}