---
title: "00_get_solar_power"
author: "Dominick J. Lemas"
date: "June 8, 2020"
output: html_document
---

Document run at: `r Sys.time()`.
Description: API system to query solar production
Website: https://www.solaredge.com/sites/default/files/se_monitoring_api.pdf
Note: This script is run during program start-up. This script is not run on schedule.  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(keyringr)
library(httr)
library(dplyr)
library(lubridate)
library(jsonlite)
library(tidyverse)
library(scales)
source("~/home-energy/utils.R")
options(scipen = 999)

# output directory
data.dir=paste0("~/home-energy/data/")

# api key
#--------
api_key=paste0("api_key=",get_API_token("solar_api"));api_key
```

```{r setup, include=FALSE}


# Solar Power Production (wats)
#---------------------------
#Description: observation every 15 minutes

solar_power_wats=sitepower(api_key, "19-10-21", "21-04-21")
solar_power_wats$date=ymd_hms(solar_power_wats$date)
save(solar_power_wats, file = paste0(data.dir,"solar.RData"))

```

This R Markdown document pulls solar data that is used by the dashboard.


   