---
title: "get-power"
author: "Dominick Lemas"
date: "7/12/2019"
output: html_document
---

Document run at: `r Sys.time()`.
Description: Emoncms API system for emoncms project

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(keyringr)
library(httr)
library(dplyr)
library(lubridate)
library(jsonlite)
library(tidyverse)
library(scales)
source("~/home-energy/code/utils/home_utils.R")
options(scipen = 999)

# https://emoncms.org/site/api#userguides

# api key
api_key=get_API_token("emoncms_api");api_key

# output directory
data.dir=paste0("~/home-energy/data/")

```


```{r}

# List feeds for authenticated user
  feedlist_url="https://emoncms.org/feed/list.json"
  KEY=paste0("&apikey=",api_key)
  feedlist_full.url=paste0(feedlist_url,KEY)
# pull data
  req <- fromJSON(feedlist_full.url)
  mydata=req %>% as.data.frame()

```

```{r}

# Run to get historical data. Missing data. 
  # January 2018 - October 2018
  # December 2018 - September 2019
  # November 2019- May 2021
  # August 2021 - present

homepower_kwh=interval_KWData(api_key, "2018-01-01", 900)

power = homepower_kwh %>%
  mutate(daily_kwh)
homepower_kwh[153451,3]- homepower_kwh[153449,3]


save(homepower_kwh, file = paste0(data.dir,"home_kwh.RData"))

```

# Data Description

Data stored: 
`r data.dir`

Start date:
`r first(homepower_kwh$date)`

End date:
`r last(homepower_kwh$date)`

# Explore the Data

```{r}
power=homepower_kwh %>%
  mutate(month=month(date),
         day=day(date))

ggplot(data = power, aes(x=date, y=kwh))+
  geom_line(color = "#00AFBB")

homepower_kwh[153451,3]- homepower_kwh[153449,3]

```


